-- Create tables

DROP TABLE IF EXISTS VData;

CREATE TABLE VData
(
	VAERS_ID INTEGER,
	RECVDATE TEXT,
	[STATE] TEXT,
	AGE_YRS REAL,
	CAGE_YR INTEGER,
	CAGE_MO REAL,
	SEX TEXT,
	RPT_DATE TEXT,
	SYMPTOM_TEXT TEXT,
	DIED TEXT,
	DATEDIED TEXT,
	L_THREAT TEXT,
	ER_VISIT TEXT,
	HOSPITAL TEXT,
	HOSPDAYS INTEGER,
	X_STAY TEXT,
	[DISABLE] TEXT,
	RECOVD TEXT,
	VAX_DATE TEXT,
	ONSET_DATE TEXT,
	NUM_DAYS INTEGER,
	LAB_DATA TEXT,
	V_ADMINBY TEXT,
	V_FUNDBY TEXT,
	OTHER_MEDS TEXT,
	CUR_ILL TEXT,
	HISTORY TEXT,
	PRIOR_VAX TEXT,
	SPLTTYPE TEXT,
	FORM_VERS INTEGER,
	TODAYS_DATE TEXT,
	BIRTH_DEFECT TEXT,
	OFC_VISIT TEXT,
	ER_ED_VISIT TEXT,
	ALLERGIES TEXT
);

DROP TABLE IF EXISTS Symptoms;

CREATE TABLE Symptoms
(
	VAERS_ID INTEGER,
	SYMPTOM1 TEXT,
	SYMPTOMVERSION1 REAL,
	SYMPTOM2 TEXT,
	SYMPTOMVERSION2 REAL,
	SYMPTOM3 TEXT,
	SYMPTOMVERSION3 REAL,
	SYMPTOM4 TEXT,
	SYMPTOMVERSION4 REAL,
	SYMPTOM5 TEXT,
	SYMPTOMVERSION5 REAL
);

DROP TABLE IF EXISTS Vaccines;

CREATE TABLE Vaccines
(
	VAERS_ID INTEGER,
	VAX_TYPE TEXT,
	VAX_MANU TEXT,
	VAX_LOT TEXT,
	VAX_DOSE_SERIES TEXT,
	VAX_ROUTE TEXT,
	VAX_SITE TEXT,
	VAX_NAME TEXT
);

-- Load data

.mode csv

.import data_sets/2021VAERSDATA.csv VData
.import data_sets/2021VAERSSYMPTOMS.csv Symptoms
.import data_sets/2021VAERSVAX.csv Vaccines

-- Drop header row entries

DELETE FROM VData WHERE VAERS_ID = 'VAERS_ID';

DELETE FROM Symptoms WHERE VAERS_ID = 'VAERS_ID';

DELETE FROM Vaccines WHERE VAERS_ID = 'VAERS_ID';

-- SQLite doesn't have a DateTime column type, so format the date columns to make them sortable (MM/DD/YYYY -> YYYY-MM-DD)

UPDATE VData SET
	RECVDATE = substr(RECVDATE,7,4) || '-' || substr(RECVDATE,1,2) || '-' || substr(RECVDATE,4,2),
	RPT_DATE = substr(RPT_DATE,7,4) || '-' || substr(RPT_DATE,1,2) || '-' || substr(RPT_DATE,4,2),
	DATEDIED = substr(DATEDIED,7,4) || '-' || substr(DATEDIED,1,2) || '-' || substr(DATEDIED,4,2),
	VAX_DATE = substr(VAX_DATE,7,4) || '-' || substr(VAX_DATE,1,2) || '-' || substr(VAX_DATE,4,2),
	ONSET_DATE = substr(ONSET_DATE,7,4) || '-' || substr(ONSET_DATE,1,2) || '-' || substr(ONSET_DATE,4,2),
	TODAYS_DATE = substr(TODAYS_DATE,7,4) || '-' || substr(TODAYS_DATE,1,2) || '-' || substr(TODAYS_DATE,4,2);
